
run:
  timeout: 5m
  go: "1.24"

issues:
  exclude-dirs:
    - vendor
    - bin
    - dist

  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - goconst
        - unparam

  exclude:
    - "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*print(f|ln)?|os\\.(Un)?Setenv). is not checked"
    - "should have a package comment, unless it's in another file for this package"

  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - gocritic
    - revive
    - unparam

  disable:
    - exhaustruct
    - exhaustive
    - lll
    - nlreturn
    - wsl
    - funlen
    - gocognit
    - cyclop
    - gocyclo
    - maintidx
    - testpackage
    - paralleltest
    - tparallel
    - prealloc
    - wrapcheck
    - forcetypeassert
    - forbidigo
    - godot
    - godox
    - varnamelen
    - interfacebloat
    - containedctx
    - contextcheck
    - depguard
    - dupl
    - nonamedreturns
    - nolintlint
    - ireturn
    - tagliatelle
    - gosec
    - nestif
    - bodyclose
    - stylecheck
    - whitespace
    - gci
    - grouper
    - importas
    - nilerr
    - nilnil
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - tenv
    - testifylint
    - thelper
    - wastedassign
    - usestdlibvars
    - zerologlint

linters-settings:
  goimports:
    local-prefixes: github.com/patrikcze/terraform-provider-veeam
  gocritic:
    enabled-checks:
      - yodaStyleExpr
  revive:
    rules:
      - name: exported
        disabled: true
      - name: package-comments
        disabled: true
