run:
  timeout: 5m

issues:
  exclude-dirs:
    - vendor
    - bin
    - dist

  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - goconst
        - unparam

  exclude:
    - "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*print(f|ln)?|os\\.(Un)?Setenv). is not checked"
    - "should have a package comment, unless it's in another file for this package"
    - "SA1019: \"io/ioutil\" has been deprecated since Go 1.19"

  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
